### ISSUE TITLE
WebUI: links to external Yandex services

### ISSUE THREAD

**Issue by oartemev** [ytsaurus/ytsaurus#102]
In the Web-UI at the page of the CHYT operation the links `Strawberry node`, `Strawberry previous operation` lead to an external Yandex service (e.g. https://h.yandex-team.ru/?%2Fnavigation%3Fpath%3D%2F%2Fsys%2Fclickhouse%2Fstrawberry%2Fch_public)

**Comment by oartemev** [comment]
@DimasKovas

**Comment by ma-efremoff** [comment]
https://nda.ya.ru/t/0hgJFxEe6kw4By

**Comment by ma-efremoff** [comment]
Fixed: https://github.com/ytsaurus/ytsaurus-ui/pull/164/commits/08f6f240756da8b6c44fb9a27cf7046910cb68d5
