### ISSUE TITLE
Floating-point numbers not shown correctly in YQL results

### ISSUE THREAD

**Issue by ibushmarinov** [ytsaurus/ytsaurus#107]
![Screenshot 2023-10-10 123142](https://github.com/ytsaurus/ytsaurus/assets/137896824/dcf248d8-ecf3-49d7-a5ff-478e53077c80)

Steps to reporoduce:

1. run
```
insert into @tmp

select CAST(0.5 as Float);

commit;
select * from @tmp 
```

2. Look at the result.

**Comment by shishovKA** [comment]
This issue is related to the user-interface, actually(
We have updated ui **stable** version (https://hub.docker.com/r/ytsaurus/ui/tags)
Problem should be gone 🤞🏻
