### ISSUE TITLE
Tmpfs volumes in CRI job environment

### ISSUE THREAD

**Issue by koct9i** [ytsaurus/ytsaurus#123]

**Comment by koct9i** [comment]
For now I see several solutions. In order from likely to be easy to hard:
1. privileged exec-node - mounts/unmounts tmpfs all by itself
2. use suid helper or sudo to mount/umount tmpfs
3. call mount/umount as CRI containers - use containerd as sudo
4. single tmpfs volume - need to create/cleanup subtrees (lack of size limit per mount)
5. CSI provisioner for maintaining tmpfs volumes - cool, but over-engineered

**Comment by zlobober** [comment]
I'd say privileged exec node is just fine. It even looks quite safe as we do not run untrusted code in exec node container, but rather in its containerd sibling.

**Comment by koct9i** [comment]
Required change in operator: https://github.com/ytsaurus/yt-k8s-operator/pull/77

**Comment by zlobober** [comment]
Can we close this?
