### ISSUE TITLE
[Bug] Use ephemeric pool in merge operations

### ISSUE THREAD

**Issue by Lesikv** [ytsaurus/ytsaurus#133]
Caused by: tech.ytsaurus.client.rpc.RpcError: 'Internal RPC call failed' <== 'Operation has failed to start' <== 'Pool name "robot-cloud.dwh.dev" must match regular expression "[-_a-z0-9:A-Z]+"'; full error:

**Comment by Kontakter** [comment]
Yes, we know about that and we will support ability to specify regex for pool names

**Comment by gritukan** [comment]
I guess there are two issues here. The first one is about regexes for pool names and the second one is about starting merge jobs outside of the SPYT pool.

**Comment by renadeen** [comment]
I have made these regular expressions configurable. Regular pool names are configured in master config. Ephemeral pool names are configured in scheduler config.
[stable/23.1](c5cf467dfe221b4d07514a00b4b2c1b703502fb9)
[stable/23.2](da35f7fcc6902e8643398b4acbce04aa70fd32ae)
[trunk](8d2fb8385096bdad32c4f1307c807a369c9af040)
