### ISSUE TITLE
Always record log message about skipped log messages as next recorded log message

### ISSUE THREAD

**Issue by koct9i** [ytsaurus/ytsaurus#144]
i.e. review logic around skipping log messages

**Comment by E1pp** [comment]
Whenever we start dropping events, log about reaching high watermark is written [here](https://github.com/ytsaurus/ytsaurus/blob/88a4537d00b6ab73293e659e4600cc75208718b0/yt/yt/core/logging/log_manager.cpp#L613). This log is written with system category so it will never be skipped.

The only other case of dropped logs is during shutdown in which case message about start of the shutdown is written to stderr.
