### ISSUE TITLE
Inefficient YSON-column processing in CHYT

### ISSUE THREAD

**Issue by achulkov2** [ytsaurus/ytsaurus#156]
I have a static table with the following characteristics: optimize_for = scan, compressed_size = 7.7G, data_weight = 283G, chunk_count ~= 500, max_block_size ~= 512KB, primary_medium = hdd, compression_codec = zstd_1.
It has a schema which includes a YSON-typed column, a thin timestamp column, as well as some other columns.

I have a CHYT clique set up to use 16 cores and 70G of memory.

With this configuration it takes around 70 seconds to perform a `select * order by `timestamp` desc limit 50` query.
If I use a map operation to convert this table to exactly the same table, but with a String column instead of the YSON column (containing the same binary yson data), the same query takes around 26 seconds to run. 

It seems like the handling of YSON columns is done inefficiently :(
Judging from the implementation, [here](https://github.com/ytsaurus/ytsaurus/blob/944e7baa833e190677a1def606baa995fad205c3/yt/chyt/server/yt_ch_converter.cpp#L216) we parse each yson-value from its binary format just to put it back in the same format later on.

Let's improve this!

**Comment by DimasKovas** [comment]
Improved in ecb39cd4e05933c5da6e87b18dc9e3b77b8ff46a by @achulkov2
