### ISSUE TITLE
if YQL operation has been in pending state for a long time, it fails with "No such transaction"

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#159]
I have YQL query like this:

```sql
USE yt;

INSERT INTO @tmp
SELECT
    COUNT(*) AS cnt
FROM 
    RANGE(`//some/dir`, `2022-01-01`, `2022-12-31`)
WHERE
    xx IS NULL;

COMMIT;

SELECT cnt
FROM @tmp;
```

Under normal conditions it works perfect, but when cluster is overloaded, I get something like this:

<img width="1819" alt="Screenshot 2023-11-15 at 10 52 45" src="https://github.com/ytsaurus/ytsaurus/assets/29466571/4658d469-ff4e-48c0-9287-88d4952baeca">

Sometimes something like this:

<img width="1823" alt="Screenshot 2023-11-15 at 10 55 27" src="https://github.com/ytsaurus/ytsaurus/assets/29466571/2e2cbca5-bd9a-45ed-8cd8-6a3ad439bbd9">

**Comment by Krisha11** [comment]
Could you please specify which version of the query_tracker image you are using?

**Comment by chegoryu** [comment]
Also I got the same error with just one long query. It fails after two minutes+ map stage.

```sql
$a = (
    SELECT
        `//a`.*, -- ...
    FROM `//a`
    ASSUME ORDER BY -- ...
);
$b = (
    SELECT
        `//b`.*, -- ...
    FROM `//b`
    ASSUME ORDER BY -- ...
);


SELECT 
    -- ...
    SOME(JoinTableRow()) AS joined_full,
FROM $a AS a
JOIN $b AS b USING (
    -- ...
)
GROUP BY (
    -- ...
)
LIMIT 50;
```

> Could you please specify which version of the query_tracker image you are using?

One moment, it is hard to find it :(
