### ISSUE TITLE
Queue agent init script creates tables in the default bundle

### ISSUE THREAD

**Issue by achulkov2** [ytsaurus/ytsaurus#166]
[This](https://github.com/ytsaurus/ytsaurus/blob/ae196ff8793aae48aafa66281019db75a3fd5cc8/yt/python/yt/environment/init_queue_agent_state.py#L4) initialization script should be parametrized with a `tablet_cell_bundle` to create tables in, which should default to `sys`.

**Comment by kaikash** [comment]
Added in https://github.com/ytsaurus/ytsaurus/pull/167. 

Should we consider updating tables we've already created with the correct tablet cell bundle in this script?
