### ISSUE TITLE
"Hydra peer is not active" when initially installing ytsaurus

### ISSUE THREAD

**Issue by hamilyon** [ytsaurus/ytsaurus#169]
Trying to install to single-node k3s using https://raw.githubusercontent.com/ytsaurus/yt-k8s-operator/main/config/samples/0.4.0/cluster_v1_demo.yaml

init-job-default successfully started, but fails after time

`ytsaurus-test-sandbox   yt-master-init-job-default-292gd                         1/1     Running     2 (73s ago)   7m10s`

`/usr/bin/yt remove //sys/@provision_lock -f` eats 100% cpu and eventually returns with

```
++ export YT_DRIVER_CONFIG_PATH=/config/client.yson
++ YT_DRIVER_CONFIG_PATH=/config/client.yson
++ /usr/bin/yt remove //sys/@provision_lock -f
Received driver response with error
    Request retries failed
        Hydra peer is not active
        Hydra peer is not active

***** Details:
Received driver response with error    
    origin          yt-master-init-job-default-292gd on 2023-11-17T10:20:14.170272Z
Request retries failed    
    code            105    
    origin          (unknown) on 2023-11-17T10:20:14.167657Z (pid 7, tid af90bc09a07e9add, fid fffef189e210d40a)    
    addresses       ['ms-0.masters.ytsaurus-test-sandbox.svc.cluster.local:9010']    
    trace_id        d2dfba8f-d836c094-c766df18-c4942847    
    kind            leader    
    span_id         8366701704633016233    
    channel_failure_error_handled true    
    omitted_inner_error_count 58
Hydra peer is not active    
    code            105    
    origin          ms-0.masters.ytsaurus-test-sandbox.svc.cluster.local on 2023-11-17T10:17:17.147177Z (pid 1, tid 335788ffe3c7ddc7, fid fffdc5f239609881)    
    request_id      e058efa7-12b91fb9-1ebeb778-7985b77a    
    connection_id   29de40a5-e4aa6f76-b5010fdc-1fcba959    
    trace_id        d2dfba8f-d836c094-c766df18-c4942847    
    span_id         6564423911144880281    
    realm_id        65726e65-ad6b7562-10259-79747361    
    timeout         30000    
    method          Execute    
    address         ms-0.masters.ytsaurus-test-sandbox.svc.cluster.local:9010    
    service         ObjectService
Hydra peer is not active    
    code            105    
    origin          ms-0.masters.ytsaurus-test-sandbox.svc.cluster.local on 2023-11-17T10:20:14.167402Z (pid 1, tid 6f37fb4774be7ed1, fid fffdc5eab20ea8f7)    
    request_id      e058efa7-12b91fb9-1ebeb778-7985b77a    
    connection_id   29de40a5-e4aa6f76-b5010fdc-1fcba959    
    trace_id        d2dfba8f-d836c094-c766df18-c4942847    
    span_id         3451498463802697946    
    realm_id        65726e65-ad6b7562-10259-79747361    
    timeout         2977    
    method          Execute    
    address         ms-0.masters.ytsaurus-test-sandbox.svc.cluster.local:9010    
    service         ObjectService
```

**Comment by hamilyon** [comment]
`yt list /` also eats 100% CPU so I guess it has same problem

**Comment by savnadya** [comment]
Hello! It looks like masters are not running successfully. Can you show please `kubectl get pod -A` and stderr of master pod (`kubectl logs <master-pod-name>`)?

**Comment by hamilyon** [comment]
Looks like the second and third master are not starting because of anti-affinity rules.

I wanted to set up using single node

```
# kubectl get events -n ytsaurus-test-sandbox
LAST SEEN   TYPE      REASON                OBJECT                                   MESSAGE
2m8s        Normal    WaitForPodScheduled   persistentvolumeclaim/master-data-ms-1   waiting for pod ms-1 to be scheduled
2m8s        Normal    WaitForPodScheduled   persistentvolumeclaim/master-data-ms-2   waiting for pod ms-2 to be scheduled
21m         Warning   FailedScheduling      pod/ms-1                                 0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
21m         Warning   FailedScheduling      pod/ms-2                                 0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..
```

**Comment by hamilyon** [comment]
Manged to start on single node by editing operator and removing anti-affinity rules for master. Not that it is a good idea, just documenting in case it helps someone else

        diff --git a/api/v1/ytsaurus_webhook.go b/api/v1/ytsaurus_webhook.go
        index 1a6f336..8fc3f4e 100644
        --- a/api/v1/ytsaurus_webhook.go
        +++ b/api/v1/ytsaurus_webhook.go
        @@ -23,7 +23,6 @@ import (
                "github.com/ytsaurus/yt-k8s-operator/pkg/consts"
                corev1 "k8s.io/api/core/v1"
                apierrors "k8s.io/apimachinery/pkg/api/errors"
        -       metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
                "k8s.io/apimachinery/pkg/runtime"
                "k8s.io/apimachinery/pkg/runtime/schema"
                "k8s.io/apimachinery/pkg/util/validation/field"
        @@ -52,24 +51,6 @@ var _ webhook.Defaulter = &Ytsaurus{}
         func (r *Ytsaurus) Default() {
                ytsauruslog.Info("default", "name", r.Name)
         
        -       // Set anti affinity for masters
        -       if r.Spec.PrimaryMasters.Affinity == nil {
        -               r.Spec.PrimaryMasters.Affinity = &corev1.Affinity{}
        -       }
        -       if r.Spec.PrimaryMasters.Affinity.PodAntiAffinity == nil {
        -               r.Spec.PrimaryMasters.Affinity.PodAntiAffinity = &corev1.PodAntiAffinity{
        -                       RequiredDuringSchedulingIgnoredDuringExecution: []corev1.PodAffinityTerm{
        -                               {
        -                                       LabelSelector: &metav1.LabelSelector{
        -                                               MatchLabels: map[string]string{
        -                                                       consts.YTComponentLabelName: fmt.Sprintf("%s-%s", r.Name, "yt-master"),
        -                                               },
        -                                       },
        -                                       TopologyKey: "kubernetes.io/hostname",
        -                               },
        -                       },
        -               }
        -       }
         }
