### ISSUE TITLE
SPYT: df.count takes too much time

### ISSUE THREAD

**Issue by Hattonuri** [ytsaurus/ytsaurus#176]
After reading dataframe df.count takes several minutes to accomplish
Table is: 8e9 rows, 600 chunks, 170gb compressed size.
12executors*16cpu ended in 2-3 minutes
when I set to 1 executor nothing changed
when i set to 1 executor 48 cpu also nothing changed

**Comment by alextokarew** [comment]
Try to set sparkConf option `spark.yt.read.ytPartitioning.enabled` to `true`

**Comment by Hattonuri** [comment]
Tried and this did not help :(

**Comment by Alexvsalexvsalex** [comment]
This commit should literally optimize count query: https://github.com/ytsaurus/ytsaurus/commit/7d7fe3bad47f6d6f75fddeed128f0acd44b51801 .
Please, try SPYT 1.75.4 which includes feature.
