### ISSUE TITLE
[Feature] Use GitHub container registry

### ISSUE THREAD

**Issue by ernado** [ytsaurus/ytsaurus#19]
I propose to use [GitHub Container Registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry) ([ghcr.io](https://ghcr.io)) instead of docker hub.

Points:
- Dockerhub has pretty strict [rate limits](https://docs.docker.com/docker-hub/download-rate-limit/) (100 pulls per 6 hours per IP address) for anonymous users
- Docker Inc. [tried to sunset](https://www.docker.com/blog/we-apologize-we-did-a-terrible-job-announcing-the-end-of-docker-free-teams/) free teams for dockerhub (but reverted under pressure)
- It is easier and safer to push images to ghcr from github pipelines
- Improved discoverability, user can instantly see all available images in "packages" section of repo or org

**Comment by savnadya** [comment]
Hello! We started to use Github Packages instead of DockerHub: https://github.com/orgs/ytsaurus/packages
