### ISSUE TITLE
Small typo in docs

### ISSUE THREAD

**Issue by zamazan4ik** [ytsaurus/ytsaurus#20]
On the page https://ytsaurus.tech/docs/en/overview/try-yt#installing-the-operator there is a small typo in the code formatting of the 2nd line - it should be `helm pull oci://docker.io/ytsaurus/top-chart --version 0.1.6 --untar` instead of `helm pull oci://docker.io/ytsaurus/top-chart --version 0.1.6 --untar' .

**Comment by gritukan** [comment]
Indeed, thank you! Don't you want to make a pull request fixing this? :)
