### ISSUE TITLE
Support for Validate & Explain in Queries

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus#223]
Subj.

Must look like a yql-specific setting which enables a special way of query running.

**Comment by zlobober** [comment]
Can we close this one?

**Comment by Krock21** [comment]
Yes. Supported from [Query Tracker 0.0.5](https://github.com/ytsaurus/ytsaurus/releases/tag/docker%2Fquery-tracker%2F0.0.5)
