### ISSUE TITLE
Replace deprecated iteritems in odin webservice

### ISSUE THREAD

**Issue by mutexed** [ytsaurus/ytsaurus#228]
Hello, in [yt_odin_webservice](https://github.com/ytsaurus/ytsaurus/blob/main/yt/odin/bin/yt_odin_webservice/__main__.py#L99) you use `parts.iteritems()`. `dict.iteritems` has been removed in python3, so you should change it to just `parts.items()` or use `iteritems` from `six` package.

**Comment by Kontakter** [comment]
I have fixed it
