### ISSUE TITLE
Confusing mistake when processing more than 32 dynamic tables within a single query

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus#240]
https://gist.github.com/zlobober/c5f782152cc19f10232730401b4b436f

Such mistake occurs when there are more than 32 (aka `spark.sql.sources.parallelPartitionDiscovery.threshold`) dynamic tables to process simultaneously.

First of all, the mistake is very confusing; if any kind of a safe limit prevents a query from executing, it should be clear which limit is exceeded and (ideally) which parameter is responsible for this limit.

Second, it is not clear why dynamic tables are any different from static tables here.

Third, it is unclear how is this issue related to the (opt-in) feature of using `partition_tables` call for slicing both static and dynamic tables. Since this option erases any distinction between static and dynamic tables, it looks like enabling it either fixes both static and dynamic cases, or breaks them simultaneously.

**Comment by Alexvsalexvsalex** [comment]
Issue was solved in this commit: https://github.com/ytsaurus/ytsaurus/commit/f8c6833e006f1edaa5ca2d3092daf74b86c35bd6 .
Information is in description.
Briefly: default was increased, partitioning support was added.
