### ISSUE TITLE
Error based on deployment

### ISSUE THREAD

**Issue by mlpxt** [ytsaurus/ytsaurus#27]
I use a single server for deployment,Here are the steps I used
Server information：
centos7.9
16G
8c
Free disk space： 200G

git clone https://github.com/ytsaurus/ytsaurus.git
cd ytsaurus/yt/docker/local
./run_local_cluster.sh

The container starts successfully，But use ip:8001 there was an error opening the webpage.

The following is the error message
----------------------------------------------
Error
Request failed with status code 500
Error

    Attributes

{
    "message": "{\"message\":\"timeout of 5000ms exceeded\",\"code\":0}"
}
-----------------------------------------------
Error
Oops! something went wrong. If the problem persists please report it via Bug Reporter.
{"message":"timeout of 5000ms exceeded","code":0}
-------------------------------------------------------

What's more, YTsaurus will exit the container of yt.bakend inexplicably after a period of time after the container is started. What is the reason for this?

Please how to solve it, look forward to your reply

**Comment by gritukan** [comment]
Hi! We do not guarantee that YTsaurus works under CentOS, so it may be better to try Ubuntu 20.04 which we are using for testing.

Nevertheless, can you please attach your logs and stderrs for further investigation? They are located inside the container in `/tmp/<some_guid>/logs` and `/tmp/<some_guid>/stderrs`.

**Comment by gritukan** [comment]
Seems like your logs were lost because you've sent them via e-mail. Can you please just attach them to github issue?

**Comment by mlpxt** [comment]
Sorry, I'll resend it
[YTlogs-stderrs.zip](https://github.com/ytsaurus/ytsaurus/files/11195148/YTlogs-stderrs.zip)

**Comment by mlpxt** [comment]
I succeeded after deploying with ubuntu.If CentOS isn't available, forget it.
Trouble for you。

**Comment by gritukan** [comment]
In logs I see the following error: `can't open "/proc/thread-self/io" with mode RdOnly|Seq (0x00000028)`. According to [man](https://man7.org/linux/man-pages/man5/proc.5.html), it is available in Linux kernel since version 3.17. What is a version of your kernel?

**Comment by mlpxt** [comment]
3.10.0-1160.el7.x86_64

**Comment by gritukan** [comment]
This kernel is almost 10 years old, we don't want to support such old configurations.
