### ISSUE TITLE
Missing repositories to build SPYT/Invalid file path

### ISSUE THREAD

**Issue by oartemev** [ytsaurus/ytsaurus#30]
Can’t build `ytsaurus-spyt` because of lack of the specific files in the referred repositories:
https://repo1.maven.org/maven2/tech/ytsaurus/ - no `spark` directory at all
https://s01.oss.sonatype.org/content/repositories/snapshots/tech/ytsaurus/spark/ - no files for `v.1.69` (e.g. https://s01.oss.sonatype.org/content/repositories/snapshots/tech/ytsaurus/spark/spark-sql_2.12/1.69.0/spark-sql_2.12-1.69.0.pom)

Also `sbt` uses the invalid paths to find `spark-catalyst` - `${fork.version}` is not resolved to the real value:
```
[error] (file-system / update) sbt.librarymanagement.ResolveException: Error downloading tech.ytsaurus.spark:spark-catalyst_2.12:${fork.version}
[error]   Not found
[error]   Not found
[error]   not found: /home/oiartemeva/.ivy2/localtech.ytsaurus.spark/spark-catalyst_2.12/${fork.version}/ivys/ivy.xml
[error]   not found: /home/oiartemeva/.m2/repository/tech/ytsaurus/spark/spark-catalyst_2.12/${fork.version}/spark-catalyst_2.12-${fork.version}.pom
[error]   not found: https://repo1.maven.org/maven2/tech/ytsaurus/spark/spark-catalyst_2.12/${fork.version}/spark-catalyst_2.12-${fork.version}.pom
[error]   not found: https://s01.oss.sonatype.org/content/repositories/snapshots/tech/ytsaurus/spark/spark-catalyst_2.12/${fork.version}/spark-catalyst_2.12-${fork.version}.pom
```

**Comment by Alexvsalexvsalex** [comment]
Now it's available
https://mvnrepository.com/artifact/tech.ytsaurus.spark/spark-core_2.12/1.69.0
https://mvnrepository.com/artifact/tech.ytsaurus.spark/spark-catalyst_2.12/1.69.0
https://mvnrepository.com/artifact/tech.ytsaurus.spark/spark-sql_2.12/1.69.0
