### ISSUE TITLE
Old SPYT version in jupyter-tutorial docker image

### ISSUE THREAD

**Issue by oartemev** [ytsaurus/ytsaurus#32]
Please update `ytsaurus/jupyter-tutorial` docker image: change the used `ytsaurus-spyt` version from _1.67.0_ to _1.69.0_.
There is only spyt v1.69 that available for pip installation. The update allows to interact with the same cluster both from the training jupyter-notebook and CLI/API.

**Comment by alextokarew** [comment]
The latest version of `ytsaurus/jupyter-tutorial` docker image is already with SPYT_VERSION=1.69.3: https://hub.docker.com/layers/ytsaurus/jupyter-tutorial/python-3.11-test-2/images/sha256-4ea759e7abcc4a55c0faf30229402387381b7d6f0e137a1ef9a55afd237181d6?context=explore#:~:text=0%20B-,59,-%7C1%20SPYT_VERSION%3D1.69.3
