### ISSUE TITLE
Odin checks issues - query_tracker_alerts, queue_agent_alerts

### ISSUE THREAD

**Issue by mutexed** [ytsaurus/ytsaurus#325]
Hello, there are minor issues in these 2 checks, both related to possible differences between cluster_name's and proxies urls.
Here is the `query_tracker_alerts` part:
```
query_tracker_stage_client = YtClient(
        proxy=cluster_name,
        token=secrets["yt_token"],
        config={"proxy": {"retries": {"count": 1, "enable": False}}})
```
I guess proxy should be ```yt_client.config["proxy"]["url"]```.

There is a required configuration for `queue_agent_alerts` check - `queue_agent_stage_clusters`, which is a list of cluster_name's (it is being compared with `options["cluster_name"]`). I guess it should be a dict where keys are cluster names, values are proxy url.

**Comment by achulkov2** [comment]
We would be happy to review and accept a PR for this issue from its author!

Otherwise, someone will get around to fixing this at some point in the foreseeable future.

**Comment by mutexed** [comment]
All fixes in trunk now, closing issue
