### ISSUE TITLE
Failed YQL query to cluster with '-' in the name

### ISSUE THREAD

**Issue by oartemev** [ytsaurus/ytsaurus#33]
The YQL query from the UI to the cluster with '-' in the name failed:
```
Error
Query 81058aa1-376b84e7-5dec3d89-c73ee972 failed[1]
YQL embedded call failed[1]
yql/library/embedded/yql_embedded.cpp:429: Failed to parse SQL: -memory-:<main>: Error: Parse Sql

    -memory-:<main>:3:5: Error: Unexpected token 'cloud' : cannot match to any predicted input...

    	from cloud-yt1.`//home/demo/chyt/uk_price_paid`;
	    ^
    -memory-:<main>:3:10: Error: Unexpected token '-' : cannot match to any predicted input...

    	from cloud-yt1.`//home/demo/chyt/uk_price_paid`;
	         ^
```
If this is the expected behavior and such naming is forbidden please describe it in the documentation.

**Comment by zlobober** [comment]
Update: you can try surrounding cluster name in backticks like the following: `cloud-yt1`.`//home/demo/chyt/uk_price_paid`

**Comment by zlobober** [comment]
Considering that there is a workaround with backticks, and nowadays you should not specify the default cluster explicitly, I'd say there is nothing left in this ticket to do.
