### ISSUE TITLE
Add information about read and write options for dynamic table in Spyt

### ISSUE THREAD

**Issue by ykuc** [ytsaurus/ytsaurus#361]
Add information in [docs](https://ytsaurus.tech/docs/ru/user-guide/data-processing/spyt/thesaurus/write-options) about read and write options for dynamic tables :

**read**
- read the last data
`.option("enable_inconsistent_read", "true") `
- read data on [timestamps](https://ytsaurus.tech/docs/en/user-guide/dynamic-tables/transactions#timestamps)
`.option("timestamp", ts)`
```

**write**
`.option("enable_inconsistent_read", "true") `

ps I can create PR by myself if you don't mind

**Comment by nadya002** [comment]
We will be glad to receive your pull request.

**Comment by ykuc** [comment]
@nadya002 add [PR](https://github.com/ytsaurus/ytsaurus/pull/756)
