### ISSUE TITLE
Add support for the `network_name` parameter in SPYT

### ISSUE THREAD

**Issue by mamogaaa** [ytsaurus/ytsaurus#366]
Currently, spark-submit-yt cannot be used when default RPC proxies are inaccessible. This issue can be resolved by allowing the inclusion of the `network_name` parameter in the /api/v4/discover_proxies request.

**Comment by Alexvsalexvsalex** [comment]
Waiting for releasing Java client with the option: https://github.com/ytsaurus/ytsaurus/pull/368
