### ISSUE TITLE
SPYT: redundant sort of the already sorted tables before join

### ISSUE THREAD

**Issue by desertfury** [ytsaurus/ytsaurus#367]
I have two tables that are already sorted by some columns and i want to join them by these exact columns.
As we can see on this screenshot, when i try to do so, there are extra sort operations before join.
[repro.pdf](https://github.com/ytsaurus/ytsaurus/files/14170052/repro.pdf)
<img width="474" alt="Screenshot 2024-02-05 at 19 28 07" src="https://github.com/ytsaurus/ytsaurus/assets/6496186/a96b2cfe-872f-450f-ad8c-02fb6589f761">

I generate sample tables using this code
```python

from enum import IntEnum
import sys
import datetime
from more_itertools import chunked
from typing import (
    Iterable,
    Optional,
)

from yt.wrapper.schema.types import (
    yt_dataclass,
    Uint8,
    Int64,
)

from yt.wrapper import YPath, TypedJob, yt_dataclass, TablePath
from yt.wrapper.schema import RowIterator, Uint64, OtherColumns, TableSchema
import yt.type_info as yt_type_info
from yt.wrapper import YtClient
from yt.wrapper.default_config import get_config_from_env

@yt_dataclass
class Row:
    market: str
    deal_id: Int64
    unix_timestamp: Int64


def main():
    final_config = get_config_from_env()
    client = YtClient(config=final_config)
    deals_table_path = '//tmp/mchichvarin/deals'
    books_table_path = '//tmp/mchichvarin/books'
    schema = TableSchema.from_row_type(Row).build_schema_sorted_by(['market', 'deal_id', 'unix_timestamp'])
    client.create('table', deals_table_path, attributes={'schema': schema}, recursive=True, force=True)
    client.create('table', books_table_path, attributes={'schema': schema}, recursive=True, force=True)

    books_rows = []
    deals_rows = []
    for i in range(100000):
        books_rows.append(Row('CME', i // 2, i))
    for i in range(10000):
        deals_rows.append(Row('CME', i * 10, i))

    print('here')
    for chunk in chunked(deals_rows, 1000):
        client.write_table_structured(TablePath(deals_table_path, append=True), Row, chunk)
    print('here')
    for chunk in chunked(books_rows, 10000):
        client.write_table_structured(TablePath(books_table_path, append=True), Row, chunk)

if __name__ == "__main__":
    sys.exit(main())
```

here is jupyter notebook with spyt query to reproduce:
https://gist.github.com/desertfury/becf93ac28685fb65f681a17c8c7b53b

If you try real life, not toy examples, there is also exchange part added to query plan, and sort stage itself will take lot more than 22ms:
<img width="562" alt="Screenshot 2024-02-05 at 19 38 47" src="https://github.com/ytsaurus/ytsaurus/assets/6496186/79369d92-77d8-46bc-a894-20c170d22f18">

**Comment by desertfury** [comment]
please, add label "query tracker" to this issue.
Thank you!

**Comment by gritukan** [comment]
@desertfury, how is this issue related to query tracker? Query tracker is a component responsible for managing, for example, YQL queries, or, in case of SPYT, Livy queries. In your notebook I see a pyspark session, it does not use query tracker in any way.

**Comment by Alexvsalexvsalex** [comment]
Please, try to set:
`spark.yt.read.keyPartitioningSortedTables.enabled` = `true`
`spark.yt.read.keyPartitioningSortedTables.unionLimit` = `1000`

**Comment by desertfury** [comment]
It does the trick for small example, but doesnt work for huge table, i.e. 
<img width="512" alt="Screenshot 2024-02-07 at 11 21 18" src="https://github.com/ytsaurus/ytsaurus/assets/6496186/7f6ab2cf-be15-44f0-8608-a6f56f392651">

**Comment by desertfury** [comment]
@Alexvsalexvsalex thanks a lot it had actually fixed the promblem for bigger table also!

**Comment by Alexvsalexvsalex** [comment]
Can you please share, what is execution time delta after successful applying plan optimization?
