### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by Sim4n6** [ytsaurus/ytsaurus#380]
Any update regarding this privately submitted security report https://github.com/ytsaurus/ytsaurus/security/advisories/GHSA-3rm6-9m2h-8g6w Please notice only the owners and the maintainers have access to it.

**Comment by DimasKovas** [comment]
Hi @Sim4n6!
Thanks for highlighting the issue. I left the response in the issue, let's continue our discussion there

**Comment by Sim4n6** [comment]
No problem
