### ISSUE TITLE
Reading in Arrow in SPYT from RPC proxies behaves differently for dynamic and static tables

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus#398]
This is incredibly surprising, but reading `timestamp` column in Arrow works for dynamic tables and does not work for static tables.

What are our plans to fix formats for dynamic tables, can you remind me? :)

**Comment by Alexvsalexvsalex** [comment]
I reproduced this in unit tests, fix will be prepared soon.

**Comment by Alexvsalexvsalex** [comment]
Fixed. Will be able in the next release. `timestamp` type was not specified as a forbidden type for arrow reading.
Colleagues tell that proxy will support all types in a nearest future.
