### ISSUE TITLE
Broken link to the documentation in yt/cpp/mapreduce/interface/operation.h

### ISSUE THREAD

**Issue by andrey-khropov** [ytsaurus/ytsaurus#422]
This line https://github.com/ytsaurus/ytsaurus/blob/215800c48f5eab62e6ecac62fa59781ecb809790/yt/cpp/mapreduce/interface/operation.h#L1205 contains a link to the https://ytsaurus.tech/docs/en/user-guide/storage/static_schema.html#schema_inference but if I try to open it I get an error 404.

**Comment by Kontakter** [comment]
Thank you for the report. I have fixed it!
