### ISSUE TITLE
Add `cluster_name` field to YQL query progress steps

### ISSUE THREAD

**Issue by Krock21** [ytsaurus/ytsaurus#425]
UI issue: https://github.com/ytsaurus/ytsaurus-ui/issues/369

Currently, YQL returns progress of an operation in the following format:
```
    "yql_progress": {
        "10": {
            "category": "yt",
            "finishedAt": "2024-03-07T17:45:45.773574Z",
            "remoteId": "",
            "stages": {},
            "startedAt": "2024-03-07T17:45:45.773574Z",
            "state": "Finished"
        },
      ....
    }
```
UI parses `remoteId` and tries to guess cluster name in order to make a link to a corresponding operation
This logic breaks for kubernetes clusters with internal remoteIds that may not have cluster name in it. We need to add a new field `cluster_name` so UI can use it

**Comment by Krock21** [comment]
I found that yql_statistics has "_cluster" parameter which is actually yt server url

```
    "yql_statistics": {
            "yt": {
                "21": {
                    "_cluster": "http-proxies.ourcluster.svc.cluster.local",
                    "_id": "7b3d316-id-here-f8b66a6e",
```

Added `_cluster_name` with cluster name there: https://github.com/ydb-platform/ydb/pull/2572

**Comment by Krock21** [comment]
We need to promote YDB commit in order for it to take effect in yql agents

**Comment by Krisha11** [comment]
Fixed in fresh QT release
