### ISSUE TITLE
[Documentation] [Bug] `YQ` used instead of `YQL`

### ISSUE THREAD

**Issue by andrey-khropov** [ytsaurus/ytsaurus#453]
At least on this page - https://ytsaurus.tech/docs/en/user-guide/storage/static-schema - `YQ` is used instead of `YQL`. 
The corresponding page in Russian - https://ytsaurus.tech/docs/ru/user-guide/storage/static-schema - uses`YQL`.

**Comment by chizhonkova** [comment]
Hi! Thank you for your issue! We will be glad to receive your pull request for such typos, sometimes it is much faster just to press the pencil button in the docs
