### ISSUE TITLE
[Documentation] "Ambient scene" makes no sense at all

### ISSUE THREAD

**Issue by andrey-khropov** [ytsaurus/ytsaurus#455]
"Ambient scene" here:

https://github.com/ytsaurus/ytsaurus/blob/74c5ce917e8bb59843df5dc6684e43e59d3f369c/yt/docs/en/_includes/user-guide/data-processing/porto/layer-paths.md?plain=1#L9

makes no sense at all.

**Comment by chizhonkova** [comment]
Hi! Could you, please, describe what you want to see here? Or what is leading to misunderstanding?
