### ISSUE TITLE
Add option to get reign for ytserver-all

### ISSUE THREAD

**Issue by l0kix2** [ytsaurus/ytsaurus#521]
It would be useful for https://github.com/ytsaurus/yt-k8s-operator/issues/200 to compare old and new image of master reign.

Something like `/usr/bin/ytserver-all --reign` would do.

**Comment by zlobober** [comment]
Let's do it in simple form only for master reigns for now.
Only for ytserver-master, let's add a flag "--dump-compatibility-info", which prints a single YSON of form:
```
{
    "current_reign" = 1234;
}
```
Relevant code:
- A function for getting current reign lives [https://github.com/ytsaurus/ytsaurus/blob/50fca7689f09efc4e2ccdd16e8a8353f70a6ee90/yt/yt/server/master/cell_master/serialize.h#L33](here).
- A code handling command-line arguments for ytserver-master lives [here](https://github.com/ytsaurus/ytsaurus/blob/50fca7689f09efc4e2ccdd16e8a8353f70a6ee90/yt/yt/server/master/cell_master/program.h#L91-L210)
- An example of dumping some information in YSON lives [here](https://github.com/ytsaurus/ytsaurus/blob/main/yt/yt/library/program/program.cpp#L214-L216)
