### ISSUE TITLE
Add list of the forbidden erasure codecs to cluster

### ISSUE THREAD

**Issue by gritukan** [ytsaurus/ytsaurus#527]
Consider a cluster with 3 racks; it is not possible to reliably store lrc_12_2_2-encoded data on it. To avoid misconfiguration it may be useful to add a list of forbidden codecs. This feature can be implemented similarly to compression codecs deprecation.

**Comment by gritukan** [comment]
>  Also it seems ok to allow any codec for non-vital data.

For non-vital data, RF=1 is the best option, I guess.

**Comment by koct9i** [comment]
> > Also it seems ok to allow any codec for non-vital data.
> 
> For non-vital data, RF=1 is the best option, I guess.

If we limit options just because data cannot be safely placed, then it is not an issue for data which don't have to be safely placed. Various codecs and replication-factor could be useful for performance aspect and/or for experiments.

**Comment by zlobober** [comment]
Let's do it in simple form -- support a blacklist of forbidden erasure codecs. It should look like a field "forbidden_erasure_codecs", similar to [this](https://github.com/ytsaurus/ytsaurus/blob/50fca7689f09efc4e2ccdd16e8a8353f70a6ee90/yt/yt/server/master/chunk_server/config.h#L583-L584) one.

Validation and its invokation points should be similar to [this] (https://github.com/ytsaurus/ytsaurus/blob/main/yt/yt/server/master/cypress_server/helpers.cpp#L443-L466).

Use this original [commit](https://github.com/ytsaurus/ytsaurus/commit/6f96de030f8b9d5665fef785a74a731d5de4d8e6) as an inspiration; though, its logic is more complicated (we do not need a logic for deprecation aliases, just the blacklist).

**Comment by gritukan** [comment]
https://github.com/ytsaurus/ytsaurus/blob/d2f5c7aea51c957f116997cdd1e93c3e66e24a62/yt/yt/server/master/table_server/table_node_type_handler_detail.cpp#L73-L76 -- also pay attention to this check, it prevents some race in case of sharded master.
