### ISSUE TITLE
Possible deadlock in TParallelUnorderedTableWriter

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#547]
Assume you added `options.ThreadCount_ + 1` write tasks to writer.

`options.ThreadCount_` tasks are running now and the last one is waiting in the `ThreadPool_` queue, i.e. all  `TaskFutures_` are not ready and this part of code always ended up in `else { break; }`

https://github.com/ytsaurus/ytsaurus/blob/d2ed6278618186e8069ad3d652a46be34bc51d21/yt/cpp/mapreduce/library/parallel_io/parallel_writer-inl.h#L204-L214

Then you call `Finish()` and start waiting for the completion of the task here: 

https://github.com/ytsaurus/ytsaurus/blob/d2ed6278618186e8069ad3d652a46be34bc51d21/yt/cpp/mapreduce/library/parallel_io/parallel_writer-inl.h#L171

After that something went wrong, for example cluster downtime/network problems/etc.

Nothing will be returned to the `WritersPool_` due to exception from `task.Process`:

https://github.com/ytsaurus/ytsaurus/blob/d2ed6278618186e8069ad3d652a46be34bc51d21/yt/cpp/mapreduce/library/parallel_io/parallel_writer-inl.h#L231-L235

And after first failed write task the last task (with `options.ThreadCount_ + 1` number) will start waiting here:

https://github.com/ytsaurus/ytsaurus/blob/d2ed6278618186e8069ad3d652a46be34bc51d21/yt/cpp/mapreduce/library/parallel_io/parallel_writer-inl.h#L251-L253

But no one will wake up this task here:

https://github.com/ytsaurus/ytsaurus/blob/d2ed6278618186e8069ad3d652a46be34bc51d21/yt/cpp/mapreduce/library/parallel_io/parallel_writer-inl.h#L273

And also `WriterPool_` will always be empty.

**Comment by Kontakter** [comment]
@dim-an – we probably have fixed it?

**Comment by dim-an** [comment]
yes, this should be fixed after 
d4c8b85ae1930b2dfe24fda4f123fdb67f37d054
