### ISSUE TITLE
./run_local_cluster.sh script doesn't work

### ISSUE THREAD

**Issue by sasorokinnebius** [ytsaurus/ytsaurus#573]
The ./run_local_cluster.sh script doesn't create a ytsaurus/local:stable container due to the `--discovery-server-count ${discovery_server_count}\` parameter on line 231 in the script.

It seems that this parameter is outdated.

**Comment by Alexvsalexvsalex** [comment]
Thank you for the report!
`ytsaurus/local:stable` doesn't have the parameter, it's available only in `ytsaurus/local:dev` still.
I removed  `discovery-server-count` from `run_local_cluster.sh` temporarily. It should work now.
