### ISSUE TITLE
Account profiling reports weird values after new accounts are added

### ISSUE THREAD

**Issue by achulkov2** [ytsaurus/ytsaurus#590]
Repro: https://github.com/ytsaurus/ytsaurus/commit/304e99ebc4a29b28917d47ddd4b9e9013791bd98.
Repro output: https://pastebin.com/JMb6Nydk.

I think the bug might be related to the new sharding logic introduced in [here](https://github.com/ytsaurus/ytsaurus/blame/main/yt/yt/server/master/security_server/security_manager.cpp#L592), since it could be impacted by the change in the order of accounts.

**Comment by H0plessFerret** [comment]
Fixed in 92e7904dddf33b5b8ec117a73c0bfdf1b774441b
