### ISSUE TITLE
Java Client tech.ytsaurus.client.YTsaurusClient Does Not Terminate

### ISSUE THREAD

**Issue by vladErmakov07** [ytsaurus/ytsaurus#606]
Hello everyone,
This issue describes a problem with the Java client tech.ytsaurus.client.YTsaurusClient and suggests possible solutions.

### Issue Description:
If the main thread of an application terminates without explicitly calling client.close(), or without using a try-with-resources block with the client as a resource (try(client) { code…}), the application will never terminate.

When debug logs are enabled, messages like the following are sent every few seconds:

```
2024-05-24 13:06:54,470 [defaultBusConnector-1-1] DEBUG tech.ytsaurus.client.rpc.DefaultRpcBusClient - Sending request ApiService/
Discover/… Session: Session(….@446b66ca)

```

If you take a jstack trace at this moment, you will notice that one of the threads is not marked as a daemon thread, and it is likely this thread that is keeping the application alive.

Example:

```
"defaultBusConnector-1-1" #26 prio=5 os_prio=0 cpu=654.61ms elapsed=39.76s tid=0x00007f8fcb069000 nid=0x76b3 runnable  [0x00007f8fb58fd000]
   java.lang.Thread.State: RUNNABLE
 at sun.nio.ch.EPoll.wait(java.base@11.0.22/Native Method)
 at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@11.0.22/EPollSelectorImpl.java:120)
 at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@11.0.22/SelectorImpl.java:124)
 - locked <0x0000000085505e58> (a io.netty.channel.nio.SelectedSelectionKeySet)
 - locked <0x0000000085827fa8> (a sun.nio.ch.EPollSelectorImpl)
 at sun.nio.ch.SelectorImpl.select(java.base@11.0.22/SelectorImpl.java:136)
 at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
 at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:824)
 at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:457)
 at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
 at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
 at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
 at java.lang.Thread.run(java.base@11.0.22/Thread.java:829)
```

### Reproduction:
To reproduce this issue, you can use the following code:

```
package tech.ytsaurus.example;

import tech.ytsaurus.client.YTsaurusClient;

public class ExampleEndlessRunningClient {
    public static void main(String[] args) {
        // You need to set up cluster address in YT_PROXY environment variable.
        var clusterAddress = System.getenv("YT_PROXY");
        if (clusterAddress == null or clusterAddress.isEmpty()) {
            throw new IllegalArgumentException("Environment variable YT_PROXY is empty");
        }

        YTsaurusClient client = YTsaurusClient.builder()
                .setCluster(clusterAddress)
                .build();

        System.out.println("Ending main method execution without explicitly calling client.close.");
    }
}

```

Please note that this issue is not visible when using the client in your integration tests with JUnit. JUnit runs and terminates tests without waiting for non-daemon threads started in the test code to finish.

### Cause of the Issue:
The problem arises due to the use of the default constructor NioEventLoopGroup (new NioEventLoopGroup(threadCount)) 
1. in the method tech.ytsaurus.client.YTsaurusClient#setDefaultBusConnectorWithThreadCount 
2. in the constructor tech.ytsaurus.client.bus.DefaultBusConnector(), which is called by default when creating YTsaurusClient. 

Since no ThreadFactory is passed in the code, it is initialized in the method io.netty.util.concurrent.MultithreadEventExecutorGroup#newDefaultThreadFactory as new DefaultThreadFactory(getClass()). 
By default, DefaultThreadFactory is created without the daemon modifier.

This DefaultThreadFactory is then used in tech.ytsaurus.client.SelfCheckingClient to form DISCOVER requests continuously, which serve no useful function after the application has terminated.

### Possible Solution:
I am attaching a pull request as an example of a possible solution.

Solution idea: Mark all netty threads as daemon

```
NioEventLoopGroup nioGroup = new NioEventLoopGroup(
        threadCount,
        new DefaultThreadFactory(DefaultBusConnector.class, true, Thread.NORM_PRIORITY)
);

```

A similar approach is implemented in the ClickHouse Java client:

**com.clickhouse.data.ClickHouseDataStreamFactory**

```
executor = ClickHouseUtils.newThreadPool("ClickHouseWorker-", coreThreads, coreThreads, 0, 0, false);
scheduler = Executors.newSingleThreadScheduledExecutor(new ClickHouseThreadFactory("ClickHouseScheduler-"));

```

Both the executor thread for current requests and the scheduler thread for background processes are marked as daemon by default. This allows resources to be explicitly closed but prevents the client from hanging if the threads are not correctly terminated.

**Comment by tinarsky** [comment]
Thank you for the bug report and PR!
