### ISSUE TITLE
Provide ability to set data_center and rack attribute for exec/tablet/data nodes via config file

### ISSUE THREAD

**Issue by dpoluyanov** [ytsaurus/ytsaurus#64]
We have plans for multiple ytsaurus clusters with different replication schemes: 3dc, single-dc-3nodes, cross-cluster.

For such setup we've created simple bootstrap program which looks into given environment and prepares appropriate config for given node: table, data, exec node. 

For now after node starts it is necessary to set attributes in cypress: `//sys/cluster_nodes/<node>/@data_center` and `//sys/cluster_nodes/<node>/@rack` in order to use rack-awareness or datacenter-aware policies.
This obliges to put cluster token into each node container as well as python and its environment, or write another tool to monitor cluster for incoming nodes and re-pin then to proper rack and datacenter. 

It would be useful to provide necessary node-placement attributes in config file as an alternative to cypress leaf

**Comment by psushin** [comment]
I would suggest to set up a stand-alone cron job, that would update cypress attributes (such as `@rack` or `@data_center`) according to your config file. That would also be more flexible, since you would be able to relabel nodes when necessary, without restarting cluster.
