### ISSUE TITLE
Allow to disable proxy discovery in go client without magic

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#65]
For now the only way to disable proxy discovery in go is to add numbers to your DNS record: https://github.com/ytsaurus/ytsaurus/blob/main/yt/go/yt/config.go#L261-L263

```go
func NormalizeProxyURL(proxy string, tvmOnly bool, tvmOnlyPort int) ClusterURL {
// ...

	if strings.ContainsAny(proxy, "0123456789") {
		url.DisableDiscovery = true
	}
// ...
```

I had to patch `/etc/hosts` to get go mapreduce client working.

Also current behavior is very non-obvious. If you suddenly have numbers in DNS records, everything works for you through the balancer, even if you wanted to work with proxies directly.

**Comment by gritukan** [comment]
Fixed in 54b321acfdc2948c97e07ddc88660123045b6937
