### ISSUE TITLE
 Making QT list_queries faster

### ISSUE THREAD

**Issue by Krisha11** [ytsaurus/ytsaurus#653]
**Problem**

Now QueryTracker UI starts working slower with a large accumulated query history.

There is a problem with the `finished_queries_by_start_time` table. At the moment, its key columns are `("start_time", "query_id")`.

list_queries does a full scan of the `finished_queries_by_start_time` table to find user's and user's acos latest queries.

```
2024-06-05 18:17:49,092121	D	Api	Listing queries (Timestamp: 1844259675235718265, State: <null>, CursorDirection: Past, FromTime: <null>, ToTime: <null>, CursorTime: <null>,Substr: <null>, User: <null>, Engine: Yql, Limit: 100, Attributes: (universal), ClientId: 8552429b-2c266e4a-972e5f0-d403893, AuthenticatedUser: mpereskokova)	Connection:3	fff8306d175becdd	239f0ad0-5b030598-1ad2ebe0-e5553a7f
```

**Propose**
As a solution, it is proposed to replace the `finished_queries_by_start_time` table with 2 others.

1) `finished_queries_by_aco_and_start_time`. Keys `("aco", "start_time", "query_id")`. Each query can correspond to several rows in the table by the number of ACOS.

2) `finished_queries_by_user_and_start_time`. Keys `("user", "start_time", "query_id")`.
_Here we can use a secondary index based on the previous table, but we can also create a separate one_

For each list_queries, there will be 3 queries in tables by key columns. In `finished_queries_by_aco_and_start_time`, `finished_queries_by_user_and_start_time` and `finished_queries`.

**Comment by Krisha11** [comment]
@Krock21, @psushin, @zlobober

**Comment by zlobober** [comment]
Discussed in SIG QT chat, LGTM.
