### ISSUE TITLE
tablet_static_.*memory.*_in_gb metrics are in bytes instead of GiB

### ISSUE THREAD

**Issue by chegoryu** [ytsaurus/ytsaurus#662]
The names of the metrics indicate that they are in `gb`:

https://github.com/ytsaurus/ytsaurus/blob/e6df8e72151031f4ea84ec50a666e6736610c4c5/yt/yt/server/master/security_server/security_manager.cpp#L663-L664

But in fact these metrics are in bytes.

I guess this is a "ctrl + c, ctrl + v" mistake:

https://github.com/ytsaurus/ytsaurus/blob/e6df8e72151031f4ea84ec50a666e6736610c4c5/yt/yt/server/master/security_server/security_manager.cpp#L657

**Comment by ifsmirnov** [comment]
These metrics are deprecated and will soon be removed in favor of per-bundle tablet resource accounting. Upcoming release of the operator will contain migration hints.

**Comment by chegoryu** [comment]
Well lucky me that I didn't have time to start using these metrics :)
