### ISSUE TITLE
Support tags with digit as first symbol in BooleanFormula

### ISSUE THREAD

**Issue by dpoluyanov** [ytsaurus/ytsaurus#71]
Sometimes we need to launch jobs on particular nodes of our YT cluster in order to test new YT versions, infrastructure changes and so on.
Using `--spec` with `scheduling_tag_filter` by node is a good point for such kind of exercise.
Major part of our YT infrastructure operates with domain names starting from number so we have `1.exec.node.fqdn`, `2.exec.node.fqdn` and so on in `//sys/cluster_nodes/<node>/@tags`.
Unfortunately, ytsaurus `scheduling_tag_filter ` doesn't support such kind of tags, failing with:
```
Error while parsing boolean formula:
2.exec.node.fqdn:9012
 ^
```
I've tested filter with different values and recorded result in table below

|filter| result| error |
|-----|-----|-----|
|--spec '{"scheduling_tag_filter"="a.1.exec.node.fqdn:9012"}'| &check; ||
|--spec '{"scheduling_tag_filter"="exec.node.fqdn:9012"}'| &check; ||
|--spec '{"scheduling_tag_filter"="1.exec.node.fqdn:9012"}'| &cross; |Error while parsing boolean formula:<br>2.exec.node.fqdn:9012<br>&nbsp;^<br>Unexpected character|
|--spec '{"scheduling_tag_filter"="127.0.0.1"}' |&cross; |Error while parsing boolean formula:<br>127.0.0.1:9012<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;^<br>Unexpected character|

If exec-node assigns these values automatically, should such tags be supported in YTsaurus?

**Comment by Kontakter** [comment]
As a solution, try to use parenthesis around literal, i.e:
```
--spec '{"scheduling_tag_filter"="(127.0.0.1)"}'
```

**Comment by dpoluyanov** [comment]
> As a solution, try to use parenthesis around literal, i.e:
> 
> ```
> --spec '{"scheduling_tag_filter"="(127.0.0.1)"}'
> ```
Unfortunately this isn't help.
Discovered the same problem is applicable to node's dynamic config too
