### ISSUE TITLE
Add whoami method to Go SDK

### ISSUE THREAD

**Issue by vitshev** [ytsaurus/ytsaurus#760]
Sometimes, we need to simply check the validity of a user’s token

**Comment by gritukan** [comment]
Hi!

It already exists (https://github.com/ytsaurus/ytsaurus/blob/969b346fa125585878d63d3e44baa81d6b583964/yt/docs/ru/_includes/faq/_includes/faq-common.md?plain=1#L262-L267C2). Seems like that the doc is in Russian only, will translate.

**Comment by zlobober** [comment]
I think Vitaly's intent was to get whoami method in Go SDK; in server-side it indeed exists for quite long time.

**Comment by l0kix2** [comment]
Some additional details:

The methods in api looks like that
```
curl -H 'Authorization: OAuth 87b2****aa5' http://my-yt-proxy/auth/whoami
{"login":"<username>","realm":"","csrf_token":"23384****92"}
```

with local yt it always returns `root`
```
~/dev/ytsaurus/yt/docker/local/run_local_cluster.sh
....
Congratulations! Local cluster is up and running. To use the cluster web interface, point your browser to http://localhost:8001. Or, if you prefer command-line tool 'yt', use it like this: 'yt --proxy localhost:8000 <command>'.

curl http://localhost:8000/auth/whoami
{"login":"root","realm":"YT","csrf_token":"aef0a9d58***2741"}
```

I suppose the new method should be added to the `AuthClient` interface and it's implementations in go sdk.
