### ISSUE TITLE
Set YT_JOB_DOCKER_IMAGE in yt operation

### ISSUE THREAD

**Issue by thenno** [ytsaurus/ytsaurus#828]
Related to https://github.com/ytsaurus/ytsaurus/pull/824

Non-binary-assembled ytsaurus-client uses pickle, which works reliably only when pickle and unpickle are performed on identical systems (like the same docker image). On the other hand, in some cases we use ytsaurus-client to run operations from another yt operation, for example in jupyter kernels.

We have started to set `YT_BASE_LAYER` in strawberry for jupyter kernels, but @zlobober suggests starting to set this variable at the job level in exec node as the generic solution.

So I would like to suggest starting to set `YT_BASE_LAYER` in a current job if there is `docker_image` in the operation spec.

**Comment by thenno** [comment]
cc @gritukan

**Comment by gritukan** [comment]
In private communication we decided to name it `YT_JOB_DOCKER_IMAGE`.

**Comment by gritukan** [comment]
Fixed in 9d56d5a5d649b30521370e1fe4761d02d20d0840.
