### ISSUE TITLE
Remove hardcoded yt.yandex-team.ru links from odin checks

### ISSUE THREAD

**Issue by Krock21** [ytsaurus/ytsaurus#833]
https://github.com/ytsaurus/ytsaurus/blob/656b8ce26f36ea69d43c0e1eb0cf72afa091e058/yt/odin/checks/lib/system_quotas/__init__.py#L78-L83

https://github.com/ytsaurus/ytsaurus/blob/656b8ce26f36ea69d43c0e1eb0cf72afa091e058/yt/odin/checks/lib/chyt_clique_liveness/__init__.py#L44

**Comment by Kontakter** [comment]
I have fixed it, thank you for the issue
