### ISSUE TITLE
Spyt ignores hive partitioning

### ISSUE THREAD

**Issue by Hattonuri** [ytsaurus/ytsaurus#86]
Assume having directory structure like this:
- root
   - field=value1
      - table
   - field=value2
      - table
   - field=value3
      - table

spark.read.*(root)

Plain spark will add "field" field to schema, but Spyt will ignore it

**Comment by Hattonuri** [comment]
I tried to add these "field" columns to all tables(they are unique within tables), but when i join two datasets with this structure, explain shows me exchange hashpartitioning using these fields. Predicate pushdown does not help

Due to all of my tables were ordered in the same way, i expected from it to use only SortMergeJoin

**Comment by alextokarew** [comment]
@Hattonuri Have you specified `.option("basePath", root)` when reading hive-partitioned data?

**Comment by alextokarew** [comment]
Tried it myself, and yes, SPYT doesn't add a partitioning column to the dataset, even with `.option("basePath", root)`. We will fix it in future releases.

**Comment by alextokarew** [comment]
@Hattonuri you should use `.option("recursiveFileLookup", "false")` instead of `.option("basePath", root)` to read Hive-partitioned data. This option is set to `true` by default in SPYT.
