### ISSUE TITLE
build on ubuntu 24.04

### ISSUE THREAD

**Issue by sguzwf** [ytsaurus/ytsaurus#899]
CMake Error at library/cpp/type_info/CMakeLists.linux-x86_64.txt:15 (find_package):
  By not providing "Findlinux-headers-generic.cmake" in CMAKE_MODULE_PATH
  this project has asked CMake to find a package configuration file provided
  by "linux-headers-generic", but CMake did not find one.

  Could not find a package configuration file provided by
  "linux-headers-generic" with any of the following names:

    linux-headers-genericConfig.cmake
    linux-headers-generic-config.cmake

  Add the installation prefix of "linux-headers-generic" to CMAKE_PREFIX_PATH
  or set "linux-headers-generic_DIR" to a directory containing one of the
  above files.  If "linux-headers-generic" provides a separate development
  package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  library/cpp/type_info/CMakeLists.txt:20

miss "Findlinux-headers-generic.cmake" ?

**Comment by Kontakter** [comment]
Hi!

I have investigated this error, it is not a problem of Ubuntu 24.04, it is a bug in build instruction (we forget to fix it after migration on conan2).

I have fixed it here: https://github.com/ytsaurus/ytsaurus/commit/f8105242b12daacc3efe15ea577e79804264e987, you can try again
