### ISSUE TITLE
Wrong parts of Python API docs

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus#915]
https://ytsaurus.tech/docs/en/api/python/start
![image](https://github.com/user-attachments/assets/9a5d391b-0e64-4185-9a91-fbf9bb8fc342)
yt todo :)
yt-fuse also seems to be missing from the package

**Comment by Kontakter** [comment]
Fixed

**Comment by zlobober** [comment]
But what about yt-fuse? Is it really there? I do not see it in my installation.

**Comment by Kontakter** [comment]
Sorry, I missed this part of question. No, it is not presented in OpenSource package, I will remove it from documentation. 

Later we will probably return it to the package, but not now since it requires some refactoring.

**Comment by Kontakter** [comment]
Now fixed
