### ISSUE TITLE
Implement OAuth usernames transformations

### ISSUE THREAD

**Issue by l0kix2** [ytsaurus/ytsaurus#926]
We have OAuth support in the server code. 
[Here](https://github.com/l0kix2/ytsaurus/blob/a60801d86879c27da10f1a9e24e35e0ecb0d9c22/yt/yt/library/auth_server/oauth_service.cpp#L127-L127) our OAuth service makes request in a remote identity server to exchange token from cookie for username. 
The issue here is that identity server may have usernames which are not suitable for ytsaurus users as is. The real world example is username if form `username@company.com` which are problematic in ytsaurus since `@` has special meaning (attribute) in ytsaurus and therefore it is hard (if even possible) to use such usernames/cypress nodes in cli/sdk/api commands, a lot of escaping issues comes up.

The proposed change is to add extra field in [TOAuthServiceConfig](https://github.com/l0kix2/ytsaurus/blob/a60801d86879c27da10f1a9e24e35e0ecb0d9c22/yt/yt/library/auth_server/config.h#L231-L231) which controls transformation info for the username field received from OAuth server and use that setting in `TOAuthService` to apply such transformation.

There can be different approaches to describe simple string manipulations in text config. In [ytsaurus-identity-sync ](https://github.com/tractoai/ytsaurus-identity-sync/blob/main/azure_config.example.yaml#L3-L7) we use `username_replacements` field with list of simple string replacements. But maybe something more generic can be used here (regex match string for example).

**Comment by achulkov2** [comment]
Implemented in #932, reassigning to me and adding Nadya as a reviewer.
