### ISSUE TITLE
Make test_yt_cli.py work

### ISSUE THREAD

**Issue by zlobober** [ytsaurus/ytsaurus#978]
Follow-up for the discussion in SIG SDK

https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/yt/wrapper/tests/ya.make#L189
depends on yt-python:
https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/yt/wrapper/testlib/helpers.py#L128-L130
https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/yt/wrapper/testlib/helpers.py#L92-L99
which is not enabled in OSS
https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/yt/wrapper/tests/ya.make#L101-L102

Probably it should be enough to remove some stuff from IF NOT OPENSOURCE, but I did not try doing that myself. So, I'd formulate this issue in more generic form -- it should be possible to run [test_yt_cli.py](https://github.com/ytsaurus/ytsaurus/blob/main/yt/python/yt/wrapper/tests/test_yt_cli.py) in OSS (at least using ya make).

**Comment by Kontakter** [comment]
I have added proper modules in OpenSource and check that tests work properly.
